"""add_notaas_project_id_to_empresas

Revision ID: 0659a14bdfbe
Revises: 80f4e3e65822
Create Date: 2026-05-08 17:38:28.283561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0659a14bdfbe'
down_revision: Union[str, None] = '80f4e3e65822'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empresas', sa.Column('notaas_project_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('empresas', 'notaas_project_id')
    # ### end Alembic commands ###
