"""refactor_monetary_to_numeric_and_sync

Revision ID: 1548e7057e6c
Revises: z005_status_pipeline_missing
Create Date: 2026-03-21 10:23:48.739692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1548e7057e6c'
down_revision: Union[str, None] = 'z005_status_pipeline_missing'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categorias_financeiras', 'ativo',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('categorias_financeiras', 'ordem',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('categorias_financeiras', 'criado_em',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_categorias_financeiras_id'), 'categorias_financeiras', ['id'], unique=False)
    op.alter_column('commercial_leads', 'valor_proposto',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('commercial_leads', 'status_pipeline',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'novo'::character varying"))
    op.alter_column('configuracoes_financeiras', 'dias_vencimento_padrao',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('7'))
    op.alter_column('configuracoes_financeiras', 'gerar_contas_ao_aprovar',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('configuracoes_financeiras', 'automacoes_ativas',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('configuracoes_financeiras', 'dias_lembrete_antes',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('2'))
    op.alter_column('configuracoes_financeiras', 'dias_lembrete_apos',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('3'))
    op.drop_constraint('configuracoes_financeiras_empresa_id_key', 'configuracoes_financeiras', type_='unique')
    op.create_index(op.f('ix_configuracoes_financeiras_empresa_id'), 'configuracoes_financeiras', ['empresa_id'], unique=True)
    op.create_index(op.f('ix_configuracoes_financeiras_id'), 'configuracoes_financeiras', ['id'], unique=False)
    op.alter_column('historico_cobrancas', 'enviado_em',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_historico_cobrancas_conta_id'), 'historico_cobrancas', ['conta_id'], unique=False)
    op.create_index(op.f('ix_historico_cobrancas_empresa_id'), 'historico_cobrancas', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_historico_cobrancas_id'), 'historico_cobrancas', ['id'], unique=False)
    op.alter_column('itens_orcamento', 'quantidade',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('itens_orcamento', 'valor_unit',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('itens_orcamento', 'total',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('movimentacoes_caixa', 'confirmado',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('movimentacoes_caixa', 'criado_em',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_movimentacoes_caixa_id'), 'movimentacoes_caixa', ['id'], unique=False)
    op.alter_column('orcamento_documentos', 'obrigatorio',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('orcamentos', 'desconto',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('orcamentos', 'total',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('orcamentos', 'valor_sinal_pix',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('saldo_caixa_configs', 'saldo_inicial',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('saldo_caixa_configs', 'configurado_em',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('saldo_caixa_configs_empresa_id_key', 'saldo_caixa_configs', type_='unique')
    op.create_index(op.f('ix_saldo_caixa_configs_id'), 'saldo_caixa_configs', ['id'], unique=False)
    op.alter_column('servicos', 'preco_padrao',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('servicos', 'preco_padrao',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.drop_index(op.f('ix_saldo_caixa_configs_id'), table_name='saldo_caixa_configs')
    op.create_unique_constraint('saldo_caixa_configs_empresa_id_key', 'saldo_caixa_configs', ['empresa_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('saldo_caixa_configs', 'configurado_em',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('saldo_caixa_configs', 'saldo_inicial',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('orcamentos', 'valor_sinal_pix',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('orcamentos', 'total',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('orcamentos', 'desconto',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('orcamento_documentos', 'obrigatorio',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_movimentacoes_caixa_id'), table_name='movimentacoes_caixa')
    op.alter_column('movimentacoes_caixa', 'criado_em',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('movimentacoes_caixa', 'confirmado',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('itens_orcamento', 'total',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('itens_orcamento', 'valor_unit',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('itens_orcamento', 'quantidade',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.drop_index(op.f('ix_historico_cobrancas_id'), table_name='historico_cobrancas')
    op.drop_index(op.f('ix_historico_cobrancas_empresa_id'), table_name='historico_cobrancas')
    op.drop_index(op.f('ix_historico_cobrancas_conta_id'), table_name='historico_cobrancas')
    op.alter_column('historico_cobrancas', 'enviado_em',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_configuracoes_financeiras_id'), table_name='configuracoes_financeiras')
    op.drop_index(op.f('ix_configuracoes_financeiras_empresa_id'), table_name='configuracoes_financeiras')
    op.create_unique_constraint('configuracoes_financeiras_empresa_id_key', 'configuracoes_financeiras', ['empresa_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('configuracoes_financeiras', 'dias_lembrete_apos',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('3'))
    op.alter_column('configuracoes_financeiras', 'dias_lembrete_antes',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('2'))
    op.alter_column('configuracoes_financeiras', 'automacoes_ativas',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('configuracoes_financeiras', 'gerar_contas_ao_aprovar',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('configuracoes_financeiras', 'dias_vencimento_padrao',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('7'))
    op.alter_column('commercial_leads', 'status_pipeline',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'novo'::character varying"))
    op.alter_column('commercial_leads', 'valor_proposto',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.drop_index(op.f('ix_categorias_financeiras_id'), table_name='categorias_financeiras')
    op.alter_column('categorias_financeiras', 'criado_em',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('categorias_financeiras', 'ordem',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('categorias_financeiras', 'ativo',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    # ### end Alembic commands ###
