"""feat: adicionar PIX aos orcamentos

Revision ID: 2dc96d88fe32
Revises: a9b8c7d6e5f4
Create Date: 2026-03-14 16:34:53.376872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dc96d88fe32'
down_revision: Union[str, None] = 'a9b8c7d6e5f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orcamentos', sa.Column('pix_chave', sa.String(length=200), nullable=True))
    op.add_column('orcamentos', sa.Column('pix_tipo', sa.String(length=20), nullable=True))
    op.add_column('orcamentos', sa.Column('pix_titular', sa.String(length=150), nullable=True))
    op.add_column('orcamentos', sa.Column('pix_qrcode', sa.Text(), nullable=True))
    op.add_column('orcamentos', sa.Column('pix_informado_em', sa.DateTime(timezone=True), nullable=True))
    op.add_column('orcamentos', sa.Column('pagamento_recebido_em', sa.DateTime(timezone=True), nullable=True))
    op.add_column('orcamentos', sa.Column('pagamento_recebido_por_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orcamentos', 'usuarios', ['pagamento_recebido_por_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orcamentos', type_='foreignkey')
    op.drop_column('orcamentos', 'pagamento_recebido_por_id')
    op.drop_column('orcamentos', 'pagamento_recebido_em')
    op.drop_column('orcamentos', 'pix_informado_em')
    op.drop_column('orcamentos', 'pix_qrcode')
    op.drop_column('orcamentos', 'pix_titular')
    op.drop_column('orcamentos', 'pix_tipo')
    op.drop_column('orcamentos', 'pix_chave')
    # ### end Alembic commands ###
