"""unify_tool_call_logs_schema

Revision ID: 4f007c9fa25f
Revises: b71dff552e45
Create Date: 2026-04-20 16:58:36.625061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4f007c9fa25f'
down_revision: Union[str, None] = 'b71dff552e45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tool_call_log_criado_em', table_name='tool_call_log')
    op.drop_index('ix_tool_call_log_empresa_id', table_name='tool_call_log')
    op.drop_index('ix_tool_call_log_id', table_name='tool_call_log')
    op.drop_index('ix_tool_call_log_sessao_id', table_name='tool_call_log')
    op.drop_index('ix_tool_call_log_status', table_name='tool_call_log')
    op.drop_index('ix_tool_call_log_tool', table_name='tool_call_log')
    op.drop_index('ix_tool_call_log_usuario_id', table_name='tool_call_log')
    op.drop_table('tool_call_log')
    op.add_column('tool_call_logs', sa.Column('usuario_id', sa.Integer(), nullable=True))
    op.add_column('tool_call_logs', sa.Column('tool', sa.String(length=100), nullable=False))
    op.add_column('tool_call_logs', sa.Column('args_json', sa.JSON(), nullable=True))
    op.add_column('tool_call_logs', sa.Column('resultado_json', sa.JSON(), nullable=True))
    op.add_column('tool_call_logs', sa.Column('status', sa.String(length=20), nullable=False))
    op.add_column('tool_call_logs', sa.Column('latencia_ms', sa.Integer(), nullable=True))
    op.add_column('tool_call_logs', sa.Column('input_tokens', sa.Integer(), nullable=True))
    op.add_column('tool_call_logs', sa.Column('output_tokens', sa.Integer(), nullable=True))
    op.add_column('tool_call_logs', sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_index('ix_tool_call_logs_tool_name', table_name='tool_call_logs')
    op.drop_index('ix_tool_call_logs_user_id', table_name='tool_call_logs')
    op.create_index(op.f('ix_tool_call_logs_criado_em'), 'tool_call_logs', ['criado_em'], unique=False)
    op.create_index(op.f('ix_tool_call_logs_status'), 'tool_call_logs', ['status'], unique=False)
    op.create_index(op.f('ix_tool_call_logs_tool'), 'tool_call_logs', ['tool'], unique=False)
    op.create_index(op.f('ix_tool_call_logs_usuario_id'), 'tool_call_logs', ['usuario_id'], unique=False)
    op.drop_constraint('tool_call_logs_user_id_fkey', 'tool_call_logs', type_='foreignkey')
    op.create_foreign_key(None, 'tool_call_logs', 'usuarios', ['usuario_id'], ['id'])
    op.drop_column('tool_call_logs', 'execution_status')
    op.drop_column('tool_call_logs', 'tool_name')
    op.drop_column('tool_call_logs', 'tool_args')
    op.drop_column('tool_call_logs', 'user_id')
    op.drop_column('tool_call_logs', 'created_at')
    op.drop_column('tool_call_logs', 'error_message')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tool_call_logs', sa.Column('error_message', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('tool_call_logs', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('tool_call_logs', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tool_call_logs', sa.Column('tool_args', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('tool_call_logs', sa.Column('tool_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('tool_call_logs', sa.Column('execution_status', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tool_call_logs', type_='foreignkey')
    op.create_foreign_key('tool_call_logs_user_id_fkey', 'tool_call_logs', 'usuarios', ['user_id'], ['id'])
    op.drop_index(op.f('ix_tool_call_logs_usuario_id'), table_name='tool_call_logs')
    op.drop_index(op.f('ix_tool_call_logs_tool'), table_name='tool_call_logs')
    op.drop_index(op.f('ix_tool_call_logs_status'), table_name='tool_call_logs')
    op.drop_index(op.f('ix_tool_call_logs_criado_em'), table_name='tool_call_logs')
    op.create_index('ix_tool_call_logs_user_id', 'tool_call_logs', ['user_id'], unique=False)
    op.create_index('ix_tool_call_logs_tool_name', 'tool_call_logs', ['tool_name'], unique=False)
    op.drop_column('tool_call_logs', 'criado_em')
    op.drop_column('tool_call_logs', 'output_tokens')
    op.drop_column('tool_call_logs', 'input_tokens')
    op.drop_column('tool_call_logs', 'latencia_ms')
    op.drop_column('tool_call_logs', 'status')
    op.drop_column('tool_call_logs', 'resultado_json')
    op.drop_column('tool_call_logs', 'args_json')
    op.drop_column('tool_call_logs', 'tool')
    op.drop_column('tool_call_logs', 'usuario_id')
    op.create_table('tool_call_log',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('empresa_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sessao_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('tool', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('args_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('resultado_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('latencia_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('input_tokens', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('output_tokens', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('criado_em', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name='tool_call_log_empresa_id_fkey'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name='tool_call_log_usuario_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='tool_call_log_pkey')
    )
    op.create_index('ix_tool_call_log_usuario_id', 'tool_call_log', ['usuario_id'], unique=False)
    op.create_index('ix_tool_call_log_tool', 'tool_call_log', ['tool'], unique=False)
    op.create_index('ix_tool_call_log_status', 'tool_call_log', ['status'], unique=False)
    op.create_index('ix_tool_call_log_sessao_id', 'tool_call_log', ['sessao_id'], unique=False)
    op.create_index('ix_tool_call_log_id', 'tool_call_log', ['id'], unique=False)
    op.create_index('ix_tool_call_log_empresa_id', 'tool_call_log', ['empresa_id'], unique=False)
    op.create_index('ix_tool_call_log_criado_em', 'tool_call_log', ['criado_em'], unique=False)
    # ### end Alembic commands ###
