"""add qr_code to notas_fiscais

Revision ID: 661b24753e61
Revises: z028_campanha_agendamento
Create Date: 2026-05-11 20:50:04.787133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '661b24753e61'
down_revision: Union[str, None] = 'z028_campanha_agendamento'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notas_fiscais', sa.Column('qr_code', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notas_fiscais', 'qr_code')
    # ### end Alembic commands ###
