"""add copiloto_user_skill

Revision ID: 6f8002896a1d
Revises: z022_unique_servico
Create Date: 2026-04-23 22:03:52.510293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f8002896a1d'
down_revision: Union[str, None] = 'z022_unique_servico'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    insp = sa.inspect(bind)
    if insp.has_table("copiloto_user_skills"):
        return
    op.create_table('copiloto_user_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('skill_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_index(op.f('ix_copiloto_user_skills_id'), 'copiloto_user_skills', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    insp = sa.inspect(bind)
    if not insp.has_table("copiloto_user_skills"):
        return
    op.drop_index(op.f('ix_copiloto_user_skills_id'), table_name='copiloto_user_skills')
    op.drop_table('copiloto_user_skills')
    # ### end Alembic commands ###
