"""add capa_template_id capa_slogan to empresas

Revision ID: 7a32aaef5122
Revises: z036_capa_portfolio
Create Date: 2026-05-15 10:58:48.286598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a32aaef5122'
down_revision: Union[str, None] = 'z036_capa_portfolio'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empresas', sa.Column('capa_template_id', sa.String(length=30), nullable=True))
    op.add_column('empresas', sa.Column('capa_slogan', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('empresas', 'capa_slogan')
    op.drop_column('empresas', 'capa_template_id')
    # ### end Alembic commands ###
