"""add_nfe_fields_empresa_and_notas_fiscais_table

Revision ID: 80f4e3e65822
Revises: z027_forma_pagamento_exibir_no_whatsapp
Create Date: 2026-05-08 16:32:16.291189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '80f4e3e65822'
down_revision: Union[str, None] = 'z027_forma_pagamento_exibir_no_whatsapp'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empresas', sa.Column('cnpj', sa.String(length=18), nullable=True))
    op.add_column('empresas', sa.Column('inscricao_estadual', sa.String(length=30), nullable=True))
    op.add_column('empresas', sa.Column('inscricao_municipal', sa.String(length=30), nullable=True))
    op.add_column('empresas', sa.Column('regime_tributario', sa.String(length=20), nullable=True))
    op.add_column('empresas', sa.Column('crt', sa.Integer(), nullable=True))
    op.add_column('empresas', sa.Column('endereco_logradouro', sa.String(length=200), nullable=True))
    op.add_column('empresas', sa.Column('endereco_numero', sa.String(length=20), nullable=True))
    op.add_column('empresas', sa.Column('endereco_complemento', sa.String(length=100), nullable=True))
    op.add_column('empresas', sa.Column('endereco_bairro', sa.String(length=100), nullable=True))
    op.add_column('empresas', sa.Column('endereco_cidade', sa.String(length=100), nullable=True))
    op.add_column('empresas', sa.Column('endereco_uf', sa.String(length=2), nullable=True))
    op.add_column('empresas', sa.Column('endereco_cep', sa.String(length=9), nullable=True))
    op.add_column('empresas', sa.Column('endereco_codigo_municipio_ibge', sa.String(length=7), nullable=True))
    op.add_column('empresas', sa.Column('notaas_api_key', sa.String(length=200), nullable=True))
    op.add_column('empresas', sa.Column('notaas_ambiente', sa.String(length=20), nullable=True))
    op.add_column('empresas', sa.Column('notaas_webhook_secret', sa.String(length=200), nullable=True))
    op.alter_column('formas_pagamento_config', 'exibir_no_whatsapp',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('notas_fiscais', 'criado_em',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('notas_fiscais', 'emitida_em',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('notas_fiscais', 'cancelada_em',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_index(op.f('ix_notas_fiscais_empresa_id'), 'notas_fiscais', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_notas_fiscais_orcamento_id'), 'notas_fiscais', ['orcamento_id'], unique=False)
    # Converter lead_score de VARCHAR para Enum requer: (1) dropar default, (2) alterar tipo, (3) recriar default
    op.execute("ALTER TABLE tenant_commercial_leads ALTER COLUMN lead_score DROP DEFAULT")
    op.execute("ALTER TABLE tenant_commercial_leads ALTER COLUMN lead_score TYPE leadscore USING lead_score::leadscore")
    op.execute("ALTER TABLE tenant_commercial_leads ALTER COLUMN lead_score SET DEFAULT 'FRIO'::leadscore")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Reverter lead_score de Enum para VARCHAR
    op.execute("ALTER TABLE tenant_commercial_leads ALTER COLUMN lead_score DROP DEFAULT")
    op.execute("ALTER TABLE tenant_commercial_leads ALTER COLUMN lead_score TYPE VARCHAR(6) USING lead_score::VARCHAR")
    op.execute("ALTER TABLE tenant_commercial_leads ALTER COLUMN lead_score SET DEFAULT 'frio'")
    op.drop_index(op.f('ix_notas_fiscais_orcamento_id'), table_name='notas_fiscais')
    op.drop_index(op.f('ix_notas_fiscais_empresa_id'), table_name='notas_fiscais')
    op.alter_column('notas_fiscais', 'cancelada_em',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('notas_fiscais', 'emitida_em',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('notas_fiscais', 'criado_em',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('formas_pagamento_config', 'exibir_no_whatsapp',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_column('empresas', 'notaas_webhook_secret')
    op.drop_column('empresas', 'notaas_ambiente')
    op.drop_column('empresas', 'notaas_api_key')
    op.drop_column('empresas', 'endereco_codigo_municipio_ibge')
    op.drop_column('empresas', 'endereco_cep')
    op.drop_column('empresas', 'endereco_uf')
    op.drop_column('empresas', 'endereco_cidade')
    op.drop_column('empresas', 'endereco_bairro')
    op.drop_column('empresas', 'endereco_complemento')
    op.drop_column('empresas', 'endereco_numero')
    op.drop_column('empresas', 'endereco_logradouro')
    op.drop_column('empresas', 'crt')
    op.drop_column('empresas', 'regime_tributario')
    op.drop_column('empresas', 'inscricao_municipal')
    op.drop_column('empresas', 'inscricao_estadual')
    op.drop_column('empresas', 'cnpj')
    # ### end Alembic commands ###
