"""Adicionar models PropostaPublica, PropostaEnviada e PropostaVisualizacao

Revision ID: 823ca6b022cd
Revises: b4255a56f865
Create Date: 2026-04-04 17:40:47.658621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '823ca6b022cd'
down_revision: Union[str, None] = 'b4255a56f865'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('propostas_publicas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=True),
    sa.Column('blocos', sa.JSON(), nullable=True),
    sa.Column('variaveis', sa.JSON(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_propostas_publicas_empresa_id'), 'propostas_publicas', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_propostas_publicas_id'), 'propostas_publicas', ['id'], unique=False)
    op.create_table('propostas_enviadas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proposta_publica_id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=36), nullable=False),
    sa.Column('dados_personalizados', sa.JSON(), nullable=True),
    sa.Column('validade_dias', sa.Integer(), nullable=True),
    sa.Column('expira_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('RASCUNHO', 'ENVIADA', 'VISUALIZADA', 'ACEITA', 'EXPIRADA', name='statusproposta'), nullable=True),
    sa.Column('aceita_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('aceita_por_nome', sa.String(length=100), nullable=True),
    sa.Column('aceita_por_email', sa.String(length=100), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['commercial_leads.id'], ),
    sa.ForeignKeyConstraint(['proposta_publica_id'], ['propostas_publicas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_propostas_enviadas_id'), 'propostas_enviadas', ['id'], unique=False)
    op.create_index(op.f('ix_propostas_enviadas_lead_id'), 'propostas_enviadas', ['lead_id'], unique=False)
    op.create_index(op.f('ix_propostas_enviadas_proposta_publica_id'), 'propostas_enviadas', ['proposta_publica_id'], unique=False)
    op.create_index(op.f('ix_propostas_enviadas_slug'), 'propostas_enviadas', ['slug'], unique=True)
    op.create_table('propostas_visualizacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proposta_enviada_id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('secao_mais_vista', sa.String(length=50), nullable=True),
    sa.Column('tempo_segundos', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['proposta_enviada_id'], ['propostas_enviadas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_propostas_visualizacoes_id'), 'propostas_visualizacoes', ['id'], unique=False)
    op.create_index(op.f('ix_propostas_visualizacoes_proposta_enviada_id'), 'propostas_visualizacoes', ['proposta_enviada_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_foreign_key(None, 'audit_logs', 'usuarios', ['usuario_id'], ['id'])
    op.create_foreign_key(None, 'audit_logs', 'empresas', ['empresa_id'], ['id'])
    op.drop_index('uq_bancos_pix_empresa_one_padrao', table_name='bancos_pix_empresa', postgresql_where='(padrao_pix = true)')
    op.drop_constraint('clientes_criado_por_id_fkey', 'clientes', type_='foreignkey')
    op.create_foreign_key(None, 'clientes', 'usuarios', ['criado_por_id'], ['id'])
    # Leads com empresa_id apontando para empresa removida/inexistente quebram o ADD CONSTRAINT.
    op.execute(
        sa.text(
            """
            UPDATE commercial_leads
            SET empresa_id = NULL
            WHERE empresa_id IS NOT NULL
              AND NOT EXISTS (
                  SELECT 1 FROM empresas e WHERE e.id = commercial_leads.empresa_id
              )
            """
        )
    )
    op.create_foreign_key(None, 'commercial_leads', 'empresas', ['empresa_id'], ['id'])
    op.alter_column('config_agendamento', 'usa_agendamento',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('empresas', 'exigir_otp_aceite',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('empresas', 'otp_valor_minimo',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_constraint('modulos_sistema_slug_key', 'modulos_sistema', type_='unique')
    op.drop_index('ix_modulos_sistema_slug', table_name='modulos_sistema')
    op.create_index(op.f('ix_modulos_sistema_slug'), 'modulos_sistema', ['slug'], unique=True)
    op.alter_column('orcamentos', 'aceite_confirmado_otp',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('orcamentos', 'exigir_otp',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_index('ix_orcamentos_empresa_pendente_liberacao', table_name='orcamentos')
    op.drop_index('uq_pagamento_fin_empresa_idempotency', table_name='pagamentos_financeiros', postgresql_where='((idempotency_key IS NOT NULL) AND (empresa_id IS NOT NULL))')
    op.drop_constraint('fk_pagamentos_financeiros_empresa_id', 'pagamentos_financeiros', type_='foreignkey')
    op.create_foreign_key(None, 'pagamentos_financeiros', 'empresas', ['empresa_id'], ['id'])
    op.alter_column('papeis', 'is_default',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('papeis', 'is_sistema',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('papeis', 'ativo',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_constraint('plano_modulos_plano_id_fkey', 'plano_modulos', type_='foreignkey')
    op.drop_constraint('plano_modulos_modulo_id_fkey', 'plano_modulos', type_='foreignkey')
    op.create_foreign_key(None, 'plano_modulos', 'modulos_sistema', ['modulo_id'], ['id'])
    op.create_foreign_key(None, 'plano_modulos', 'planos', ['plano_id'], ['id'])
    op.alter_column('usuarios', 'permissoes',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuarios', 'permissoes',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_constraint(None, 'plano_modulos', type_='foreignkey')
    op.drop_constraint(None, 'plano_modulos', type_='foreignkey')
    op.create_foreign_key('plano_modulos_modulo_id_fkey', 'plano_modulos', 'modulos_sistema', ['modulo_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('plano_modulos_plano_id_fkey', 'plano_modulos', 'planos', ['plano_id'], ['id'], ondelete='CASCADE')
    op.alter_column('papeis', 'ativo',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('papeis', 'is_sistema',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('papeis', 'is_default',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_constraint(None, 'pagamentos_financeiros', type_='foreignkey')
    op.create_foreign_key('fk_pagamentos_financeiros_empresa_id', 'pagamentos_financeiros', 'empresas', ['empresa_id'], ['id'], ondelete='SET NULL')
    op.create_index('uq_pagamento_fin_empresa_idempotency', 'pagamentos_financeiros', ['empresa_id', 'idempotency_key'], unique=True, postgresql_where='((idempotency_key IS NOT NULL) AND (empresa_id IS NOT NULL))')
    op.create_index('ix_orcamentos_empresa_pendente_liberacao', 'orcamentos', ['empresa_id', 'agendamento_opcoes_pendente_liberacao'], unique=False)
    op.alter_column('orcamentos', 'exigir_otp',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('orcamentos', 'aceite_confirmado_otp',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_modulos_sistema_slug'), table_name='modulos_sistema')
    op.create_index('ix_modulos_sistema_slug', 'modulos_sistema', ['slug'], unique=False)
    op.create_unique_constraint('modulos_sistema_slug_key', 'modulos_sistema', ['slug'], postgresql_nulls_not_distinct=False)
    op.alter_column('empresas', 'otp_valor_minimo',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('empresas', 'exigir_otp_aceite',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('config_agendamento', 'usa_agendamento',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_constraint(None, 'commercial_leads', type_='foreignkey')
    op.drop_constraint(None, 'clientes', type_='foreignkey')
    op.create_foreign_key('clientes_criado_por_id_fkey', 'clientes', 'usuarios', ['criado_por_id'], ['id'], ondelete='SET NULL')
    op.create_index('uq_bancos_pix_empresa_one_padrao', 'bancos_pix_empresa', ['empresa_id'], unique=True, postgresql_where='(padrao_pix = true)')
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_propostas_visualizacoes_proposta_enviada_id'), table_name='propostas_visualizacoes')
    op.drop_index(op.f('ix_propostas_visualizacoes_id'), table_name='propostas_visualizacoes')
    op.drop_table('propostas_visualizacoes')
    op.drop_index(op.f('ix_propostas_enviadas_slug'), table_name='propostas_enviadas')
    op.drop_index(op.f('ix_propostas_enviadas_proposta_publica_id'), table_name='propostas_enviadas')
    op.drop_index(op.f('ix_propostas_enviadas_lead_id'), table_name='propostas_enviadas')
    op.drop_index(op.f('ix_propostas_enviadas_id'), table_name='propostas_enviadas')
    op.drop_table('propostas_enviadas')
    op.drop_index(op.f('ix_propostas_publicas_id'), table_name='propostas_publicas')
    op.drop_index(op.f('ix_propostas_publicas_empresa_id'), table_name='propostas_publicas')
    op.drop_table('propostas_publicas')
    # ### end Alembic commands ###
