"""feat: adicionar pix padrao a empresa

Revision ID: 8b8efeace516
Revises: 2dc96d88fe32
Create Date: 2026-03-14 17:14:56.097560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b8efeace516'
down_revision: Union[str, None] = '2dc96d88fe32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empresas', sa.Column('pix_chave_padrao', sa.String(length=200), nullable=True))
    op.add_column('empresas', sa.Column('pix_tipo_padrao', sa.String(length=20), nullable=True))
    op.add_column('empresas', sa.Column('pix_titular_padrao', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('empresas', 'pix_titular_padrao')
    op.drop_column('empresas', 'pix_tipo_padrao')
    op.drop_column('empresas', 'pix_chave_padrao')
    # ### end Alembic commands ###
