"""feat: adiciona pix_payload ao orcamento (EMV BRCode)

Revision ID: 8f19ab3f4b99
Revises: 8b8efeace516
Create Date: 2026-03-14 18:23:10.089558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f19ab3f4b99'
down_revision: Union[str, None] = '8b8efeace516'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orcamentos', sa.Column('pix_payload', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orcamentos', 'pix_payload')
    # ### end Alembic commands ###
