"""feat: adiciona assinatura_email a empresa

Revision ID: a07fa98d3427
Revises: 8f19ab3f4b99
Create Date: 2026-03-14 19:02:25.257734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a07fa98d3427'
down_revision: Union[str, None] = '8f19ab3f4b99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empresas', sa.Column('assinatura_email', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('empresas', 'assinatura_email')
    # ### end Alembic commands ###
