"""add_sessao_whatsapp

Revision ID: aa51e0f91548
Revises: tc008_add_anexo_to_tenant_templates
Create Date: 2026-05-07 19:41:20.106396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa51e0f91548'
down_revision: Union[str, None] = 'tc008_add_anexo_to_tenant_templates'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessao_whatsapp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('etapa', sa.String(length=50), nullable=False),
    sa.Column('contexto', sa.JSON(), nullable=False),
    sa.Column('expira_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessao_whatsapp_empresa_id'), 'sessao_whatsapp', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_sessao_whatsapp_id'), 'sessao_whatsapp', ['id'], unique=False)
    op.create_index(op.f('ix_sessao_whatsapp_telefone'), 'sessao_whatsapp', ['telefone'], unique=True)
    op.alter_column('tenant_commercial_leads', 'lead_score',
               existing_type=sa.VARCHAR(length=6),
               type_=sa.Enum('QUENTE', 'MORNO', 'FRIO', name='leadscore'),
               existing_nullable=True,
               existing_server_default=sa.text("'frio'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenant_commercial_leads', 'lead_score',
               existing_type=sa.Enum('QUENTE', 'MORNO', 'FRIO', name='leadscore'),
               type_=sa.VARCHAR(length=6),
               existing_nullable=True,
               existing_server_default=sa.text("'frio'::character varying"))
    op.drop_index(op.f('ix_sessao_whatsapp_telefone'), table_name='sessao_whatsapp')
    op.drop_index(op.f('ix_sessao_whatsapp_id'), table_name='sessao_whatsapp')
    op.drop_index(op.f('ix_sessao_whatsapp_empresa_id'), table_name='sessao_whatsapp')
    op.drop_table('sessao_whatsapp')
    # ### end Alembic commands ###
