"""add_notif_whats_visualizacao_to_empresas

Revision ID: ac64aef565f2
Revises: e60f737b701c
Create Date: 2026-03-14 00:53:08.841983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac64aef565f2'
down_revision: Union[str, None] = 'e60f737b701c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empresas', sa.Column('notif_whats_visualizacao', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('empresas', 'notif_whats_visualizacao')
    # ### end Alembic commands ###
