"""Add status_envio to CommercialLead

Revision ID: b633b63e31e4
Revises: b66af2e00a10
Create Date: 2026-03-20 09:40:26.515829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b633b63e31e4'
down_revision: Union[str, None] = 'b66af2e00a10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commercial_leads', sa.Column('status_envio', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('commercial_leads', 'status_envio')
    # ### end Alembic commands ###
