"""add campaigns tables

Revision ID: b66af2e00a10
Revises: f4ef69a06e14
Create Date: 2026-03-19 21:52:06.338820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision: str = 'b66af2e00a10'
down_revision: Union[str, None] = 'f4ef69a06e14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def column_exists(table_name, column_name):
    """Verifica se uma coluna existe na tabela."""
    inspector = inspect(op.get_bind())
    columns = [col['name'] for col in inspector.get_columns(table_name)]
    return column_name in columns


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # campaign_leads
    if not column_exists('campaign_leads', 'status'):
        op.add_column('campaign_leads', sa.Column('status', sa.String(length=20), nullable=True))
    if not column_exists('campaign_leads', 'data_envio'):
        op.add_column('campaign_leads', sa.Column('data_envio', sa.DateTime(timezone=True), nullable=True))
    if not column_exists('campaign_leads', 'data_entrega'):
        op.add_column('campaign_leads', sa.Column('data_entrega', sa.DateTime(timezone=True), nullable=True))
    if not column_exists('campaign_leads', 'data_resposta'):
        op.add_column('campaign_leads', sa.Column('data_resposta', sa.DateTime(timezone=True), nullable=True))
    if not column_exists('campaign_leads', 'criado_em'):
        op.add_column('campaign_leads', sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))

    # campaigns
    if not column_exists('campaigns', 'status'):
        op.add_column('campaigns', sa.Column('status', sa.String(length=20), nullable=True))
    if not column_exists('campaigns', 'total_leads'):
        op.add_column('campaigns', sa.Column('total_leads', sa.Integer(), nullable=True))
    if not column_exists('campaigns', 'enviados'):
        op.add_column('campaigns', sa.Column('enviados', sa.Integer(), nullable=True))
    if not column_exists('campaigns', 'entregues'):
        op.add_column('campaigns', sa.Column('entregues', sa.Integer(), nullable=True))
    if not column_exists('campaigns', 'respondidos'):
        op.add_column('campaigns', sa.Column('respondidos', sa.Integer(), nullable=True))
    if not column_exists('campaigns', 'criado_em'):
        op.add_column('campaigns', sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    if not column_exists('campaigns', 'atualizado_em'):
        op.add_column('campaigns', sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True))

    # lead_importacao_itens
    if not column_exists('lead_importacao_itens', 'status'):
        op.add_column('lead_importacao_itens', sa.Column('status', sa.String(length=20), nullable=True))
    if not column_exists('lead_importacao_itens', 'erro'):
        op.add_column('lead_importacao_itens', sa.Column('erro', sa.Text(), nullable=True))
    if not column_exists('lead_importacao_itens', 'lead_id'):
        op.add_column('lead_importacao_itens', sa.Column('lead_id', sa.Integer(), nullable=True))
        op.create_index(op.f('ix_lead_importacao_itens_lead_id'), 'lead_importacao_itens', ['lead_id'], unique=False)
        op.create_foreign_key(None, 'lead_importacao_itens', 'commercial_leads', ['lead_id'], ['id'])
    if not column_exists('lead_importacao_itens', 'criado_em'):
        op.add_column('lead_importacao_itens', sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lead_importacao_itens', type_='foreignkey')
    op.drop_index(op.f('ix_lead_importacao_itens_lead_id'), table_name='lead_importacao_itens')
    op.drop_column('lead_importacao_itens', 'criado_em')
    op.drop_column('lead_importacao_itens', 'lead_id')
    op.drop_column('lead_importacao_itens', 'erro')
    op.drop_column('lead_importacao_itens', 'status')
    op.drop_column('campaigns', 'atualizado_em')
    op.drop_column('campaigns', 'criado_em')
    op.drop_column('campaigns', 'respondidos')
    op.drop_column('campaigns', 'entregues')
    op.drop_column('campaigns', 'enviados')
    op.drop_column('campaigns', 'total_leads')
    op.drop_column('campaigns', 'status')
    op.drop_column('campaign_leads', 'criado_em')
    op.drop_column('campaign_leads', 'data_resposta')
    op.drop_column('campaign_leads', 'data_entrega')
    op.drop_column('campaign_leads', 'data_envio')
    op.drop_column('campaign_leads', 'status')
    # ### end Alembic commands ###
