"""Add preco_mercado_livre

Revision ID: cb1bf41ded7b
Revises: tc011_whatsapp_conversa_vista_tenant_leads
Create Date: 2026-05-14 14:14:04.038097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb1bf41ded7b'
down_revision: Union[str, None] = 'tc011_whatsapp_conversa_vista_tenant_leads'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servicos', sa.Column('preco_mercado_livre', sa.Numeric(precision=10, scale=2), nullable=True))
    op.alter_column('servicos', 'dados_fiscais_ok',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('servicos', 'dados_fiscais_ok',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_column('servicos', 'preco_mercado_livre')
    # ### end Alembic commands ###
