"""feat: add planes and modules system

Revision ID: e11faf9b0ad1
Revises: z010_config_global
Create Date: 2026-03-23 02:45:40.197298

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e11faf9b0ad1"
down_revision: Union[str, None] = "z010_config_global"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Garante colunas antes de rodar os inserts
    op.execute("ALTER TABLE empresas ADD COLUMN IF NOT EXISTS plano_id INTEGER")
    op.execute(
        "ALTER TABLE empresas ADD COLUMN IF NOT EXISTS total_mensagens_whatsapp INTEGER DEFAULT 0"
    )
    op.execute(
        "ALTER TABLE empresas ADD COLUMN IF NOT EXISTS ultima_atividade_em TIMESTAMP WITH TIME ZONE"
    )
    op.execute(
        "ALTER TABLE empresas ADD COLUMN IF NOT EXISTS total_mensagens_ia INTEGER DEFAULT 0"
    )

    # Garante que as tabelas existem
    op.execute("""
        CREATE TABLE IF NOT EXISTS modulos_sistema (
            id SERIAL PRIMARY KEY,
            nome VARCHAR(100) NOT NULL,
            slug VARCHAR(50) UNIQUE,
            descricao TEXT,
            ativo BOOLEAN DEFAULT TRUE
        )
    """)
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_modulos_sistema_id ON modulos_sistema (id)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_modulos_sistema_slug ON modulos_sistema (slug)"
    )

    op.execute("""
        CREATE TABLE IF NOT EXISTS planos (
            id SERIAL PRIMARY KEY,
            nome VARCHAR(100) NOT NULL,
            descricao TEXT,
            limite_usuarios INTEGER DEFAULT 1,
            limite_orcamentos INTEGER DEFAULT 50,
            total_mensagem_ia INTEGER DEFAULT 100,
            total_mensagem_whatsapp INTEGER DEFAULT 500,
            preco_mensal NUMERIC(10, 2) DEFAULT 0,
            ativo BOOLEAN DEFAULT TRUE,
            criado_em TIMESTAMP WITH TIME ZONE DEFAULT now()
        )
    """)
    op.execute("CREATE INDEX IF NOT EXISTS ix_planos_id ON planos (id)")

    op.execute("""
        CREATE TABLE IF NOT EXISTS plano_modulos (
            plano_id INTEGER REFERENCES planos(id) ON DELETE CASCADE,
            modulo_id INTEGER REFERENCES modulos_sistema(id) ON DELETE CASCADE,
            PRIMARY KEY (plano_id, modulo_id)
        )
    """)

    # Re-adiciona FK caso tenha falhado
    try:
        op.create_foreign_key(None, "empresas", "planos", ["plano_id"], ["id"])
    except:
        pass

    # --- SCRIPT DE MIGRAÇÃO DE DADOS ---
    # 1. Inserir Módulos Padrão
    op.execute(
        "INSERT INTO modulos_sistema (nome, slug, ativo) VALUES ('Orçamentos', 'orcamentos', true) ON CONFLICT (slug) DO NOTHING"
    )
    op.execute(
        "INSERT INTO modulos_sistema (nome, slug, ativo) VALUES ('Clientes', 'clientes', true) ON CONFLICT (slug) DO NOTHING"
    )
    op.execute(
        "INSERT INTO modulos_sistema (nome, slug, ativo) VALUES ('Catálogo', 'catalogo', true) ON CONFLICT (slug) DO NOTHING"
    )
    op.execute(
        "INSERT INTO modulos_sistema (nome, slug, ativo) VALUES ('Financeiro', 'financeiro', true) ON CONFLICT (slug) DO NOTHING"
    )
    op.execute(
        "INSERT INTO modulos_sistema (nome, slug, ativo) VALUES ('Assistente IA', 'ia', true) ON CONFLICT (slug) DO NOTHING"
    )
    op.execute(
        "INSERT INTO modulos_sistema (nome, slug, ativo) VALUES ('WhatsApp Próprio', 'whatsapp', true) ON CONFLICT (slug) DO NOTHING"
    )
    op.execute(
        "INSERT INTO modulos_sistema (nome, slug, ativo) VALUES ('Relatórios', 'relatorios', true) ON CONFLICT (slug) DO NOTHING"
    )

    # 2. Inserir Planos Padrão
    op.execute(
        "DELETE FROM planos WHERE nome IN ('Trial', 'Starter', 'Pro', 'Business')"
    )

    op.execute(
        "INSERT INTO planos (nome, limite_usuarios, limite_orcamentos, total_mensagem_ia, total_mensagem_whatsapp, preco_mensal, ativo) VALUES ('Trial', 1, 50, 100, 0, 0, true)"
    )
    op.execute(
        "INSERT INTO planos (nome, limite_usuarios, limite_orcamentos, total_mensagem_ia, total_mensagem_whatsapp, preco_mensal, ativo) VALUES ('Starter', 3, 200, 100, 0, 97, true)"
    )
    op.execute(
        "INSERT INTO planos (nome, limite_usuarios, limite_orcamentos, total_mensagem_ia, total_mensagem_whatsapp, preco_mensal, ativo) VALUES ('Pro', 10, 1000, 500, 2000, 197, true)"
    )
    op.execute(
        "INSERT INTO planos (nome, limite_usuarios, limite_orcamentos, total_mensagem_ia, total_mensagem_whatsapp, preco_mensal, ativo) VALUES ('Business', 999, 9999, 2000, 5000, 397, true)"
    )

    # 3. Vincular Empresas atuais aos novos Planos (case insensitive)
    op.execute("""
        UPDATE empresas 
        SET plano_id = (SELECT id FROM planos WHERE LOWER(planos.nome) = LOWER(empresas.plano) LIMIT 1)
        WHERE empresas.plano IS NOT NULL AND (empresas.plano_id IS NULL)
    """)

    # 4. Vincular Módulos aos Planos (Relacionamentos)
    op.execute(
        "INSERT INTO plano_modulos (plano_id, modulo_id) SELECT p.id, m.id FROM planos p, modulos_sistema m WHERE m.slug IN ('orcamentos', 'clientes', 'catalogo') ON CONFLICT DO NOTHING"
    )
    op.execute(
        "INSERT INTO plano_modulos (plano_id, modulo_id) SELECT p.id, m.id FROM planos p, modulos_sistema m WHERE p.nome IN ('Starter', 'Pro', 'Business') AND m.slug = 'relatorios' ON CONFLICT DO NOTHING"
    )
    op.execute(
        "INSERT INTO plano_modulos (plano_id, modulo_id) SELECT p.id, m.id FROM planos p, modulos_sistema m WHERE p.nome IN ('Pro', 'Business') AND m.slug IN ('ia', 'whatsapp') ON CONFLICT DO NOTHING"
    )
    op.execute(
        "INSERT INTO plano_modulos (plano_id, modulo_id) SELECT p.id, m.id FROM planos p, modulos_sistema m WHERE p.nome = 'Business' AND m.slug = 'financeiro' ON CONFLICT DO NOTHING"
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.drop_constraint(None, "empresas", type_="foreignkey")
    except:
        pass
    op.execute("ALTER TABLE empresas DROP COLUMN IF EXISTS total_mensagens_whatsapp")
    op.execute("ALTER TABLE empresas DROP COLUMN IF EXISTS ultima_atividade_em")
    op.execute("ALTER TABLE empresas DROP COLUMN IF EXISTS plano_id")
    op.drop_table("plano_modulos")
    op.drop_index(op.f("ix_planos_id"), table_name="planos")
    op.drop_table("planos")
    op.drop_index(op.f("ix_modulos_sistema_slug"), table_name="modulos_sistema")
    op.drop_index(op.f("ix_modulos_sistema_id"), table_name="modulos_sistema")
    op.drop_table("modulos_sistema")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "empresas", type_="foreignkey")
    op.drop_column("empresas", "total_mensagens_whatsapp")
    op.drop_column("empresas", "plano_id")
    op.drop_table("plano_modulos")
    op.drop_index(op.f("ix_planos_id"), table_name="planos")
    op.drop_table("planos")
    op.drop_index(op.f("ix_modulos_sistema_slug"), table_name="modulos_sistema")
    op.drop_index(op.f("ix_modulos_sistema_id"), table_name="modulos_sistema")
    op.drop_table("modulos_sistema")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "usuarios",
        sa.Column(
            "perm_catalogo",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_constraint(None, "servicos", type_="foreignkey")
    op.drop_column("servicos", "categoria_id")
    op.drop_column("servicos", "preco_custo")
    op.drop_constraint(None, "empresas", type_="foreignkey")
    op.drop_column("empresas", "total_mensagens_whatsapp")
    op.drop_column("empresas", "total_mensagens_ia")
    op.drop_column("empresas", "ultima_atividade_em")
    op.drop_column("empresas", "plano_id")
    op.drop_constraint(None, "clientes", type_="foreignkey")
    op.drop_index(op.f("ix_clientes_criado_por_id"), table_name="clientes")
    op.drop_column("clientes", "criado_por_id")
    op.drop_index(op.f("ix_audit_logs_usuario_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_empresa_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_criado_em"), table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index(
        op.f("ix_categorias_catalogo_empresa_id"), table_name="categorias_catalogo"
    )
    op.drop_table("categorias_catalogo")
    op.drop_table("plano_modulos")
    op.drop_index(op.f("ix_planos_id"), table_name="planos")
    op.drop_table("planos")
    op.drop_index(op.f("ix_modulos_sistema_slug"), table_name="modulos_sistema")
    op.drop_index(op.f("ix_modulos_sistema_id"), table_name="modulos_sistema")
    op.drop_table("modulos_sistema")
    op.drop_table("config_global")
    # ### end Alembic commands ###
