"""add missing columns after stamp

Revision ID: e60f737b701c
Revises: 001_initial
Create Date: 2026-03-14 00:28:28.250418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e60f737b701c'
down_revision: Union[str, None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Use batch for clientes alter_column
    with op.batch_alter_table('clientes') as batch_op:
        batch_op.alter_column('endereco',
                   existing_type=sa.VARCHAR(length=300),
                   type_=sa.String(length=500),
                   existing_nullable=True)
    
    # Add columns to empresas (SQLite supports this directly)
    op.add_column('empresas', sa.Column('desconto_max_percent', sa.Integer(), nullable=True))
    op.add_column('empresas', sa.Column('descricao_publica_empresa', sa.Text(), nullable=True))
    op.add_column('empresas', sa.Column('texto_aviso_aceite', sa.Text(), nullable=True))
    op.add_column('empresas', sa.Column('mostrar_botao_whatsapp', sa.Boolean(), nullable=True))
    op.add_column('empresas', sa.Column('texto_assinatura_proposta', sa.String(length=200), nullable=True))
    op.add_column('empresas', sa.Column('mensagem_confianca_proposta', sa.Text(), nullable=True))
    op.add_column('empresas', sa.Column('mostrar_mensagem_confianca', sa.Boolean(), nullable=True))
    
    # Use batch for empresas alter_column and unique constraint
    with op.batch_alter_table('empresas') as batch_op:
        batch_op.alter_column('ativo',
                   existing_type=sa.BOOLEAN(),
                   nullable=True,
                   existing_server_default=sa.text('true'))
        # Constraint addition
        batch_op.create_unique_constraint('uq_empresas_evolution_instance_v2', ['evolution_instance'])

    op.drop_index('uq_empresas_evolution_instance', table_name='empresas', postgresql_where='(evolution_instance IS NOT NULL)')
    op.create_index(op.f('ix_empresas_telefone_operador'), 'empresas', ['telefone_operador'], unique=False)
    
    # Use batch for historico_edicoes
    with op.batch_alter_table('historico_edicoes') as batch_op:
        batch_op.alter_column('editado_por_id',
                   existing_type=sa.INTEGER(),
                   nullable=True)
    
    op.drop_index('idx_historico_orcamento', table_name='historico_edicoes')
    op.drop_index('idx_log_email_orcamento', table_name='log_email_orcamento')
    op.drop_index('idx_log_email_status', table_name='log_email_orcamento')
    op.create_index(op.f('ix_notificacoes_empresa_id'), 'notificacoes', ['empresa_id'], unique=False)
    
    # Add column to orcamentos
    op.add_column('orcamentos', sa.Column('approved_notification_sent_at', sa.DateTime(timezone=True), nullable=True))
    
    with op.batch_alter_table('orcamentos') as batch_op:
        batch_op.drop_index('ix_orcamentos_numero')
        batch_op.create_index(op.f('ix_orcamentos_numero'), ['numero'], unique=False)
        batch_op.create_index(op.f('ix_orcamentos_link_publico'), ['link_publico'], unique=False)

    # Add column to usuarios
    op.add_column('usuarios', sa.Column('desconto_max_percent', sa.Integer(), nullable=True))
    
    with op.batch_alter_table('usuarios') as batch_op:
        batch_op.alter_column('is_superadmin',
                   existing_type=sa.BOOLEAN(),
                   nullable=True,
                   existing_server_default=sa.text('false'))
        batch_op.drop_index('idx_usuarios_reset_senha_token_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios') as batch_op:
        batch_op.create_index('idx_usuarios_reset_senha_token_hash', ['reset_senha_token_hash'], unique=False)
        batch_op.alter_column('is_superadmin',
                   existing_type=sa.BOOLEAN(),
                   nullable=False,
                   existing_server_default=sa.text('false'))
        batch_op.drop_column('desconto_max_percent')

    with op.batch_alter_table('orcamentos') as batch_op:
        batch_op.drop_index(op.f('ix_orcamentos_link_publico'))
        batch_op.drop_index(op.f('ix_orcamentos_numero'))
        batch_op.create_index('ix_orcamentos_numero', ['numero'], unique=True)
        batch_op.drop_column('approved_notification_sent_at')

    op.drop_index(op.f('ix_notificacoes_empresa_id'), table_name='notificacoes')
    op.create_index('idx_log_email_status', 'log_email_orcamento', ['status'], unique=False)
    op.create_index('idx_log_email_orcamento', 'log_email_orcamento', ['orcamento_id'], unique=False)
    op.create_index('idx_historico_orcamento', 'historico_edicoes', ['orcamento_id'], unique=False)
    
    with op.batch_alter_table('historico_edicoes') as batch_op:
        batch_op.alter_column('editado_por_id',
                   existing_type=sa.INTEGER(),
                   nullable=False)
    
    with op.batch_alter_table('empresas') as batch_op:
        batch_op.drop_constraint('uq_empresas_evolution_instance_v2', type_='unique')
        batch_op.drop_index(op.f('ix_empresas_telefone_operador'))
        batch_op.alter_column('ativo',
                   existing_type=sa.BOOLEAN(),
                   nullable=False,
                   existing_server_default=sa.text('true'))
        batch_op.drop_column('mostrar_mensagem_confianca')
        batch_op.drop_column('mensagem_confianca_proposta')
        batch_op.drop_column('texto_assinatura_proposta')
        batch_op.drop_column('mostrar_botao_whatsapp')
        batch_op.drop_column('texto_aviso_aceite')
        batch_op.drop_column('descricao_publica_empresa')
        batch_op.drop_column('desconto_max_percent')

    op.create_index('uq_empresas_evolution_instance', 'empresas', ['evolution_instance'], unique=True, postgresql_where='(evolution_instance IS NOT NULL)')
    
    with op.batch_alter_table('clientes') as batch_op:
        batch_op.alter_column('endereco',
                   existing_type=sa.String(length=500),
                   type_=sa.VARCHAR(length=300),
                   existing_nullable=True)
    # ### end Alembic commands ###
