"""Add unique partial index to categoria_financeira

Revision ID: f4ef69a06e14
Revises: f985249b1289
Create Date: 2026-03-17 23:54:43.270095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4ef69a06e14'
down_revision: Union[str, None] = 'f985249b1289'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Desativar categorias duplicadas mais antigas antes de adicionar a constraint única
    op.execute("""
        UPDATE categorias_financeiras
        SET ativo = FALSE
        WHERE id IN (
            SELECT id
            FROM (
                SELECT
                    id,
                    ROW_NUMBER() OVER (PARTITION BY empresa_id, nome, tipo ORDER BY criado_em DESC) as rn
                FROM categorias_financeiras
                WHERE ativo = TRUE
            ) AS sub
            WHERE sub.rn > 1
        );
    """)
    op.create_index('uq_categoria_nome_tipo_empresa', 'categorias_financeiras', ['empresa_id', 'nome', 'tipo'], unique=True, postgresql_where=sa.text('ativo = true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_categoria_nome_tipo_empresa', table_name='categorias_financeiras', postgresql_where=sa.text('ativo = true'))
    # ### end Alembic commands ###
