"""fix: preencher_tipo_categorias_nulas

Revision ID: f985249b1289
Revises: j001
Create Date: 2026-03-17 23:25:03.970153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f985249b1289'
down_revision: Union[str, None] = 'j001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE categorias_financeiras SET tipo = 'despesa' WHERE tipo IS NULL OR tipo = '';")
    op.drop_index('ix_categorias_financeiras_ativo', table_name='categorias_financeiras')
    op.drop_index('ix_categorias_financeiras_tipo', table_name='categorias_financeiras')
    op.drop_index('idx_clientes_empresa_id', table_name='clientes')
    op.alter_column('commercial_leads', 'ativo',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('contas_financeiras', 'valor_pago',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('contas_financeiras', 'status',
               existing_type=postgresql.ENUM('pendente', 'parcial', 'pago', 'vencido', 'cancelado', name='statusconta'),
               nullable=True,
               existing_server_default=sa.text("'pendente'::statusconta"))
    op.alter_column('contas_financeiras', 'origem',
               existing_type=postgresql.ENUM('manual', 'whatsapp', 'assistente_ia', 'webhook', 'sistema', name='origemregistro'),
               nullable=True,
               existing_server_default=sa.text("'sistema'::origemregistro"))
    op.drop_index('ix_contas_empresa_status', table_name='contas_financeiras')
    op.drop_index('ix_contas_empresa_vencimento', table_name='contas_financeiras')
    op.drop_index('ix_contas_financeiras_cancelado_em', table_name='contas_financeiras')
    op.drop_index('ix_contas_financeiras_excluido_em', table_name='contas_financeiras')
    op.alter_column('empresas', 'notif_whats_visualizacao',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_index('uq_empresas_evolution_instance', table_name='empresas', postgresql_where='(evolution_instance IS NOT NULL)')
    op.create_unique_constraint(None, 'empresas', ['evolution_instance'])
    op.alter_column('formas_pagamento_config', 'ativo',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('formas_pagamento_config', 'aceita_parcelamento',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('formas_pagamento_config', 'max_parcelas',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('formas_pagamento_config', 'taxa_percentual',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('formas_pagamento_config', 'gera_pix_qrcode',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('formas_pagamento_config', 'ordem',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('formas_pagamento_config', 'padrao',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('formas_pagamento_config', 'exigir_entrada_na_aprovacao',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('formas_pagamento_config', 'percentual_entrada',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('formas_pagamento_config', 'percentual_saldo',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.drop_index('idx_historico_orcamento', table_name='historico_edicoes')
    op.drop_index('idx_log_email_orcamento', table_name='log_email_orcamento')
    op.drop_index('idx_log_email_status', table_name='log_email_orcamento')
    op.drop_index('ix_movimentacoes_caixa_data', table_name='movimentacoes_caixa')
    op.drop_index('ix_movimentacoes_caixa_tipo', table_name='movimentacoes_caixa')
    op.drop_index('idx_notificacoes_empresa_lida', table_name='notificacoes')
    op.drop_index('ix_notificacoes_empresa_lida', table_name='notificacoes')
    op.create_index(op.f('ix_notificacoes_empresa_id'), 'notificacoes', ['empresa_id'], unique=False)
    op.drop_index('idx_orcamentos_empresa_status', table_name='orcamentos')
    op.drop_index('idx_orcamentos_link_publico', table_name='orcamentos')
    op.drop_index('idx_orcamentos_status', table_name='orcamentos')
    op.drop_index('ix_orcamentos_empresa_criado', table_name='orcamentos')
    op.drop_index('ix_orcamentos_empresa_numero', table_name='orcamentos', postgresql_where='(numero IS NOT NULL)')
    op.drop_index('ix_orcamentos_empresa_status', table_name='orcamentos')
    op.create_index(op.f('ix_orcamentos_link_publico'), 'orcamentos', ['link_publico'], unique=False)
    op.drop_constraint('fk_orcamentos_regra_pagamento_id', 'orcamentos', type_='foreignkey')
    op.create_foreign_key(None, 'orcamentos', 'formas_pagamento_config', ['regra_pagamento_id'], ['id'])
    op.alter_column('pagamentos_financeiros', 'tipo',
               existing_type=postgresql.ENUM('sinal', 'parcela', 'quitacao', name='tipopagamento'),
               nullable=True,
               existing_server_default=sa.text("'quitacao'::tipopagamento"))
    op.alter_column('pagamentos_financeiros', 'origem',
               existing_type=postgresql.ENUM('manual', 'whatsapp', 'assistente_ia', 'webhook', 'sistema', name='origemregistro'),
               nullable=True,
               existing_server_default=sa.text("'manual'::origemregistro"))
    op.alter_column('pagamentos_financeiros', 'status',
               existing_type=postgresql.ENUM('confirmado', 'estornado', name='statuspagamentofinanceiro'),
               nullable=True,
               existing_server_default=sa.text("'confirmado'::statuspagamentofinanceiro"))
    op.alter_column('templates_notificacao', 'ativo',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_index('idx_usuarios_reset_senha_token_hash', table_name='usuarios')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_usuarios_reset_senha_token_hash', 'usuarios', ['reset_senha_token_hash'], unique=False)
    op.alter_column('templates_notificacao', 'ativo',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('pagamentos_financeiros', 'status',
               existing_type=postgresql.ENUM('confirmado', 'estornado', name='statuspagamentofinanceiro'),
               nullable=False,
               existing_server_default=sa.text("'confirmado'::statuspagamentofinanceiro"))
    op.alter_column('pagamentos_financeiros', 'origem',
               existing_type=postgresql.ENUM('manual', 'whatsapp', 'assistente_ia', 'webhook', 'sistema', name='origemregistro'),
               nullable=False,
               existing_server_default=sa.text("'manual'::origemregistro"))
    op.alter_column('pagamentos_financeiros', 'tipo',
               existing_type=postgresql.ENUM('sinal', 'parcela', 'quitacao', name='tipopagamento'),
               nullable=False,
               existing_server_default=sa.text("'quitacao'::tipopagamento"))
    op.drop_constraint(None, 'orcamentos', type_='foreignkey')
    op.create_foreign_key('fk_orcamentos_regra_pagamento_id', 'orcamentos', 'formas_pagamento_config', ['regra_pagamento_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_orcamentos_link_publico'), table_name='orcamentos')
    op.create_index('ix_orcamentos_empresa_status', 'orcamentos', ['empresa_id', 'status'], unique=False)
    op.create_index('ix_orcamentos_empresa_numero', 'orcamentos', ['empresa_id', 'numero'], unique=True, postgresql_where='(numero IS NOT NULL)')
    op.create_index('ix_orcamentos_empresa_criado', 'orcamentos', ['empresa_id', sa.text('criado_em DESC')], unique=False)
    op.create_index('idx_orcamentos_status', 'orcamentos', ['status'], unique=False)
    op.create_index('idx_orcamentos_link_publico', 'orcamentos', ['link_publico'], unique=False)
    op.create_index('idx_orcamentos_empresa_status', 'orcamentos', ['empresa_id', 'status'], unique=False)
    op.drop_index(op.f('ix_notificacoes_empresa_id'), table_name='notificacoes')
    op.create_index('ix_notificacoes_empresa_lida', 'notificacoes', ['empresa_id', 'lida'], unique=False)
    op.create_index('idx_notificacoes_empresa_lida', 'notificacoes', ['empresa_id', 'lida'], unique=False)
    op.create_index('ix_movimentacoes_caixa_tipo', 'movimentacoes_caixa', ['tipo'], unique=False)
    op.create_index('ix_movimentacoes_caixa_data', 'movimentacoes_caixa', ['data'], unique=False)
    op.create_index('idx_log_email_status', 'log_email_orcamento', ['status'], unique=False)
    op.create_index('idx_log_email_orcamento', 'log_email_orcamento', ['orcamento_id'], unique=False)
    op.create_index('idx_historico_orcamento', 'historico_edicoes', ['orcamento_id'], unique=False)
    op.alter_column('formas_pagamento_config', 'percentual_saldo',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('formas_pagamento_config', 'percentual_entrada',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('formas_pagamento_config', 'exigir_entrada_na_aprovacao',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('formas_pagamento_config', 'padrao',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('formas_pagamento_config', 'ordem',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('formas_pagamento_config', 'gera_pix_qrcode',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('formas_pagamento_config', 'taxa_percentual',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('formas_pagamento_config', 'max_parcelas',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('formas_pagamento_config', 'aceita_parcelamento',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('formas_pagamento_config', 'ativo',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_constraint(None, 'empresas', type_='unique')
    op.create_index('uq_empresas_evolution_instance', 'empresas', ['evolution_instance'], unique=True, postgresql_where='(evolution_instance IS NOT NULL)')
    op.alter_column('empresas', 'notif_whats_visualizacao',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.create_index('ix_contas_financeiras_excluido_em', 'contas_financeiras', ['excluido_em'], unique=False)
    op.create_index('ix_contas_financeiras_cancelado_em', 'contas_financeiras', ['cancelado_em'], unique=False)
    op.create_index('ix_contas_empresa_vencimento', 'contas_financeiras', ['empresa_id', 'data_vencimento'], unique=False)
    op.create_index('ix_contas_empresa_status', 'contas_financeiras', ['empresa_id', 'status'], unique=False)
    op.alter_column('contas_financeiras', 'origem',
               existing_type=postgresql.ENUM('manual', 'whatsapp', 'assistente_ia', 'webhook', 'sistema', name='origemregistro'),
               nullable=False,
               existing_server_default=sa.text("'sistema'::origemregistro"))
    op.alter_column('contas_financeiras', 'status',
               existing_type=postgresql.ENUM('pendente', 'parcial', 'pago', 'vencido', 'cancelado', name='statusconta'),
               nullable=False,
               existing_server_default=sa.text("'pendente'::statusconta"))
    op.alter_column('contas_financeiras', 'valor_pago',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('commercial_leads', 'ativo',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.create_index('idx_clientes_empresa_id', 'clientes', ['empresa_id'], unique=False)
    op.create_index('ix_categorias_financeiras_tipo', 'categorias_financeiras', ['tipo'], unique=False)
    op.create_index('ix_categorias_financeiras_ativo', 'categorias_financeiras', ['ativo'], unique=False)
    # ### end Alembic commands ###
